version: '2'
services:
  users:
      container_name: php_users
      build:
          dockerfile: Dockerfile
          context: ./users
      volumes:
          - ./users/:/var/www
  site:
      container_name: php_site
      build:
          dockerfile: Dockerfile
          context: ./site
      ports:
          - 80:8080
      volumes:
          - ./site/:/var/www
      links:
          - users